### ISSUE TITLE
Stateful boolean flag does not get toggled

### ISSUE THREAD

**Issue by raunofreiberg** [uber/react-view#19]
I noticed this when trying to use `react-view` with Modal. The same issue can be found in [baseweb example of Modal](https://baseweb.design/components/modal/).

**Steps to reproduce:**
1. Check the `isOpen` knob to true
2. Modal opens
3. Close the modal
4. Re-check the `isOpen` knob to true
5. Modal does not open

**Example**

![image](https://gyazo.com/611500842e94d0387e83c541bd16d801.gif)

**Comment by tajo** [comment]
Oh yea, I saw this too but forgot to create a ticket for it. Thanks for reminding me.

**Comment by raunofreiberg** [comment]
It seems like [this line](https://github.com/uber/react-view/blob/master/src/use-view.ts#L97) is relevant.

I changed `updatePropsAndCodeNoRecompile` to `updatePropsAndCode` and tried the build in baseweb.design and the described issue was resolved.

Although, I'm not sure if there is a specific reason not to compile in this case?

**Comment by tajo** [comment]
> Although, I'm not sure if this is the best way to solve it. Is there a specific reason not to recompile?

Yea, the component would get re-mounted and lose the focus. So for example, you would not be able to type into the `Input` component without constantly losing the focus.

I think we might need to just fix the `Modal` so it checks the state in `onDidUpdate`.

**Comment by pat-son** [comment]
> I think we might need to just fix the Modal so it checks the state in componentDidUpdate.

We just encountered this issue today, with our functional, hooks-based Modal component. I don't think the answer should be to change the component's implementation because it's react-view that's broken, not the Modal.

**Comment by tajo** [comment]
Looking into this now
