### ISSUE TITLE
Feature Request: Multiple PropTypes for a prop

### ISSUE THREAD

**Issue by aditya81070** [uber/react-view#34]
I am using `react-view` for live(interactive) component documentation. I feel that there are cases where a prop can accept multiple types of values or a mixture of values. I don't know this is available or not. (if it is please tell me otherwise is it possible to add this feature)

# Example 1
For a `Select` component  if I take an array of objects as `options` prop then I have to set type to `PropTypes.Array` but I want to set it to `PropTypes.Array(PropTypes.object)` so it can be aligned with my internal propTypes.

# Example 2
For the same `Select` component, I will internally use empty string for single select and empty array for multiselect. In this condition, I have a `value` prop that can either `PropTypes.string` or `PropTypes.Array(PropTypes.String)` according to type  of select.

**Comment by raunofreiberg** [comment]
I might be missing something here, but why do you need to specify the value of the items in the array? Using a generic `PropTypes.Array` does not place any constraints on the signature of the array, and should suffice for both — array of objects and array of strings.

**Comment by tajo** [comment]
react-view proptypes are mostly used to render an appropriate UI knob. Boolean gives you a checkbox, enum gives you a select/radio and almost everything else gives you just a textarea. So when you have a complex type, you can always fallback to `PropTypes.Object`. 

You could also do some customization and [introduce your own PropType](https://react-view.netlify.com/?path=/story/advanced--custom-prop) and related knob.

**Comment by aditya81070** [comment]
Okay, I got the point. It is just to show the UI according to `PropTypes.type` not actual type checking. Thankyou @tajo and @raunofreiberg.
Closing the issue in respect of @raunofreiberg and @tajo's explanation.
