### ISSUE TITLE
Maximum call stack size exceeded when using React.forwardRef

### ISSUE THREAD

**Issue by raunofreiberg** [uber/react-view#35]
Self-explanatory title. I haven't looked into why this happens, but here is a re-producible example: https://baseweb.design/components/tooltip/?code=import%20*%20as%20React%20from%20%22react%22%3B%0Aimport%20%7B%20StatefulTooltip%20%7D%20from%20%22baseui%2Ftooltip%22%3B%0Aimport%20%7B%20Input%20%7D%20from%20%22baseui%2Finput%22%3B%0A%0Aconst%20Button%20%3D%20React.forwardRef((props%2C%20ref)%20%3D%3E%20%3Cbutton%20%7B...props%7D%20ref%3D%7Bref%7D%20%2F%3E)%0A%0Aexport%20default%20()%20%3D%3E%20%7B%0A%20%20return%20(%0A%20%20%20%20%3CStatefulTooltip%0A%20%20%20%20%20%20content%3D%7B()%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%3CBlock%20padding%3D%7B%2220px%22%7D%3E%0A%20%20%20%20%20%20%20%20%20%20Hello%2C%20there!%20%F0%9F%91%8B%0A%20%20%20%20%20%20%20%20%20%20%3CInput%20placeholder%3D%22Focusable%20Element%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FBlock%3E%0A%20%20%20%20%20%20)%7D%0A%20%20%20%20%20%20returnFocus%0A%20%20%20%20%20%20autoFocus%0A%20%20%20%20%3E%0A%20%20%20%20%20%20Hover%20me%0A%20%20%20%20%3C%2FStatefulTooltip%3E%0A%20%20)%3B%0A%7D

**Comment by tajo** [comment]
This is not really about `React.forwardRef`. You can remove it and still see the same error.

The real problem is that you can't have any other statement outside of `export default` block (except imports). react-view doesn't support ES modules, it just fakes it. It actually takes the code, strips imports, strips `export default` and puts the rest into `new Function()` call.

You could move the button inside of the main component.

**Comment by raunofreiberg** [comment]
Hmm.. I removed the `React.forwardRef` and the error goes away, so it is possible to define components outside the export.

https://baseweb.design/components/tooltip/?code=import%20*%20as%20React%20from%20%22react%22%3B%0Aimport%20%7B%20StatefulTooltip%20%7D%20from%20%22baseui%2Ftooltip%22%3B%0Aimport%20%7B%20Input%20%7D%20from%20%22baseui%2Finput%22%3B%0A%0Aconst%20Button%20%3D%20()%20%3D%3E%20%3Cbutton%3Ehey%3C%2Fbutton%3E%0A%0Aexport%20default%20()%20%3D%3E%20%7B%0A%20%20return%20(%0A%20%20%20%20%3CStatefulTooltip%0A%20%20%20%20%20%20content%3D%7B()%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%3CBlock%20padding%3D%7B%2220px%22%7D%3E%0A%20%20%20%20%20%20%20%20%20%20Hello%2C%20there!%20%F0%9F%91%8B%0A%20%20%20%20%20%20%20%20%20%20%3CInput%20placeholder%3D%22Focusable%20Element%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FBlock%3E%0A%20%20%20%20%20%20)%7D%0A%20%20%20%20%20%20returnFocus%0A%20%20%20%20%20%20autoFocus%0A%20%20%20%20%3E%0A%20%20%20%20%20%20Hover%20me%0A%20%20%20%20%3C%2FStatefulTooltip%3E%0A%20%20)%3B%0A%7D

**Comment by tajo** [comment]
Well now it renders the button only and not the tooltip which is not something anyone would expect.

Btw, if you click on "Copy URL" button, you'll get a shorter URL to share.

**Comment by raunofreiberg** [comment]
Ah, my bad. I'll close the issue now, thanks! 🙈
