### ISSUE TITLE
Support for installing with npm

### ISSUE THREAD

**Issue by xanderfehsenfeld** [uber/react-view#5]
# Support for installing with npm
Will you support installing with `npm`? I am having difficulty installing: 

## Steps to recreate:
1. Create a new project in an empty directory with `npm init`
2. run `npm i -D react-view`

## Expected behavior
A successful install.

## Actual behavior:
Throws an error with the output:
```
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '<REDACTED>/node_modules/@miksu/prettier/bin/prettier.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!    /<REDACTED>/.npm/_logs/2019-12-05T20_40_29_878Z-debug.log
```
## Attempted fix
I attempted to fix this by running `npm i -D @miksu/prettier` but the install fails with the same output as above.

**Comment by tajo** [comment]
Should work now!
