### ISSUE TITLE
Nested dependency is packaged and published through github which is a potential security risk

### ISSUE THREAD

**Issue by danchan159** [uber/react-view#54]
Hi react-view team, could you help with this?

I'm looking to use this library in my firm. As part of the process to use this library internally, react-view and it's dependencies need to be onboarded as a security measure. Our onboarding process does not allow dependencies to be resolved through github and instead must come through trusted repos like npm. 

I've made a proposed solution in this prettier dependency that is causing the issue, please take a look at this pr I made for this dependency. https://github.com/tajo/prettier/pull/1

Thanks,
Daniel

**Comment by rezaabedian** [comment]
This is also effecting me! Our organisation doesn't allow us to onboard libraries if they have dependencies that are git based. Would appreciate it someone could address this!

**Comment by tajo** [comment]
Thanks for the PR. It should be resolved with `react-view@2.3.4`
