### ISSUE TITLE
How to change the theme?

### ISSUE THREAD

**Issue by lengkaixin** [uber/react-view#59]
How to change the theme like baseUI? For example, replace the <button /> in the ActionButton component with the <Button /> in your own component library? thank you very much!

**Comment by tajo** [comment]
You should use `useView` hook and pass data/props to your own custom components. This library is really just that hook handling the whole state. Default UI components are pretty easily replaceable if you wish.

https://react-view.netlify.app/?path=/story/useview--basic

If you are specifically interested into Base Web's theme, you can check out our implementation: https://github.com/uber/baseweb/tree/master/documentation-site/components/yard

**Comment by lengkaixin** [comment]
thank you very much！
