### ISSUE TITLE
useView doesn't work in next js

### ISSUE THREAD

**Issue by hetanthakkar1** [uber/react-view#67]
![image](https://user-images.githubusercontent.com/38756320/113158450-6b9b0c00-9259-11eb-899a-007064040cb2.png)

**Comment by hetanthakkar1** [comment]
This is the code to reporduce the error in Next Js:

import * as React from "react";

import {
  useView,
  Compiler,
  Knobs,
  Editor,
  Error,
  ActionButtons,
  Placeholder,
  PropTypes,
} from "react-view";

import { Button, SIZE } from "./button";

function App() {
  const params = useView({
    componentName: "Button",
    props: {
      children: {
        value: "Hello",
        type: PropTypes.ReactNode,
        description: "Visible label.",
      },
      size: {
        value: "SIZE.default",
        defaultValue: "SIZE.default",
        options: SIZE,
        type: PropTypes.Enum,
        description: "Defines the size of the button.",
        imports: {
          "your-button-component": {
            named: ["SIZE"],
          },
        },
      },
      onClick: {
        value: '() => alert("click")',
        type: PropTypes.Function,
        description: "Function called when button is clicked.",
      },
      disabled: {
        value: false,
        type: PropTypes.Boolean,
        description: "Indicates that the button is disabled",
      },
    },
    scope: {
      Button,
      SIZE,
    },
    imports: {
      "your-button-component": {
        named: ["Button"],
      },
    },
  });

  const decoratorsPreset = () => ({
    plugins: [[require("@babel/plugin-proposal-decorators"), { legacy: true }]],
  });

  return (
    <div style={{ maxWidth: "600px", margin: "0px auto" }}>
      <Compiler
        {...params.compilerProps}
        presets={[decoratorsPreset]}
        minHeight={62}
        placeholder={Placeholder}
      />
      <Error msg={params.errorProps.msg} isPopup />
      <Knobs {...params.knobProps} />
      <Editor {...params.editorProps} />
      <Error {...params.errorProps} />
      <ActionButtons {...params.actions} />
    </div>
  );
}
export default App;

**Comment by tajo** [comment]
We use `Next v10` + `react-view` for https://baseweb.design. Your issue might be something else. You should create a repro.

**Comment by hetanthakkar1** [comment]
@tajo You are correct it was  mistake on my side! Thank you

**Comment by raunofreiberg** [comment]
@hetanthakkar1 How did you solve this? I'm still getting it. I've configured `next.config.js` but no luck:

```js
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    return config;
  },
};
```

@tajo Here's a reproducible Next.js 11 app → https://github.com/raunofreiberg/react-view-next-11

To be clear, this is the error I'm seeing:

![image](https://user-images.githubusercontent.com/23662329/135663461-6e447c5d-5cb4-430e-9626-d60d6d43e63f.png)

**Comment by hetanthakkar1** [comment]
@raunofreiberg You really think that our errors are same!? my error message indicated that the problem was due to useView on line 17 i don't see your error indicating that it's because of useView

**Comment by raunofreiberg** [comment]
It seems like the error resolves when I don't use yarn instead of npm. Odd. Digging more.

**Comment by raunofreiberg** [comment]
If I delete React & ReactDOM (16.14.0) from `node_modules/react-view` then the error resolves. OTOH, Yarn doesn't install mismatched version of React under the project. 🤔 

<img width="247" alt="CleanShot 2021-10-01 at 15 20 11@2x" src="https://user-images.githubusercontent.com/23662329/135668642-2c25d2ab-6f8a-445f-8993-f8c668df8cd5.png">
