### ISSUE TITLE
Unable to use additional  presets

### ISSUE THREAD

**Issue by singharpit94** [uber/react-view#7]
Hi , I am trying to use babel plugin-proposal-decorator

Following is the code snippet I am trying to use

```
export default () => {
    const params = useView({
        initialCode: code,
        scope: {},
        onUpdate: console.log
    });
    const presets = {
        plugins: [[require("@babel/plugin-proposal-decorators"), {legacy: true}]]
    };
    return (
        <React.Fragment>
            <Compiler {...params.compilerProps} presets={[presets]} />
            <Editor {...params.editorProps} language="tsx" />
            <Error {...params.errorProps} />
        </React.Fragment>
    );
};


```

Basically I am trying to use autobind decorator for my react class components passed as initial code to useView hook.

Can someone help here?

**Comment by tajo** [comment]
The API is slightly different:

https://codesandbox.io/s/i3dbn?fontsize=14&hidenavigation=1&theme=dark

Although, this still doesn't work becuase `babel/parser` needs to add `decorators` flag. [Docs](https://babeljs.io/docs/en/babel-parser). That's not currently exposed through as a public API but could be. Do you want to try open a PR?

**Comment by singharpit94** [comment]
Thanks for the api issue fix, but even if I add decorators-legacy in ast.js file in babelParse method plugin, I could not get it working , You can reproduce the issue in your code sandbox snippet too by using @autobind decorator. Let me know if I am missing anything obvious here.

**Comment by singharpit94** [comment]
Probably I got this, currently the compiler can only support React Elements only and not exact decorated code, correct me if I am wrong

**Comment by tajo** [comment]
@singhalpriyank Yea it doesn't work because parser needs to be extended. I mentioned it in my previous comment:

> Although, this still doesn't work becuase babel/parser needs to add decorators flag. Docs. That's not currently exposed through as a public API but could be. Do you want to try open a PR?
