### ISSUE TITLE
PropTypes.Object does not behave as expected.

### ISSUE THREAD

**Issue by peterjcoffman** [uber/react-view#8]
I cannot seem to get Object props to work properly. When I enter an object into the text input, I always get an error popup reading:

```
TypeError: Property expression of JSXExpressionContainer expected node to be of a type ["Expression","JSXEmptyExpression"] but instead got "BlockStatement"
```

In order to ensure the problem isn't on my end, I forked the CodeSandbox example in the README:
https://codesandbox.io/s/react-view-useview-basic-usage-ygizd
I added a new prop, called "foo" with type of PropTypes.Object. When an object (i.e. {hello: 'world'}) is entered into the knob, it gives an error.

I have tested this on Firefox 71.0 and Chrome 78.

It is possible I am simply using this incorrectly, but none of the examples show how to use an Object knob. The only place I can see an Object prop used in the codebase is in `code-generator.test.ts`.

**Comment by tajo** [comment]
Looks like bug. It should be probably treated the same way as ReactNode.
