### ISSUE TITLE
Some strings are not permissible enum keys

### ISSUE THREAD

**Issue by peterjcoffman** [uber/react-view#9]
In my application, I am using an enum to allow the user to select between several possible strings, some of which contain `-` characters. Here is an example of an enum I might have:

```
options: {
    ['left']: 'left',
    ['top-left']: 'top-left',
    etc...
}
```

If I then select 'top-left', this will fail the error: `ReferenceError: left is not defined`

Here's a demo forked from your CodeSandbox:

https://codesandbox.io/s/react-view-useview-basic-usage-kmze8

Select 'compact-broken' to see the error.

So it seems like only strings that would be valid JS identifiers work as enum keys. This means nothing containing `-`, nothing starting with a number, nothing starting with `(`, etc.

I believe this can be fixed by accessing enums using bracket notation rather than dot notation.

EDIT: Or, at least, using bracket notation would solve _my_ problem. There are some things that might need to be escaped.

**Comment by tajo** [comment]
good catch, definitely a bug
